[package]
name = "pqp"
version = "0.1.0"
edition = "2021"

[lib]
name = "pqp"
crate-type = ["cdylib"]

[dependencies]
cute = "0.3.0"
rand = "0.8.5"
itertools = "0.4.3"
# ytesrev = "0.2.7"

[dependencies.pyo3]
version = "0.17.3"
features = ["extension-module", "abi3-py37"]
