# name: docs

# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main


# jobs:
#     update_docs:
#         runs-on: ubuntu-latest
#         steps:
#             - uses: actions/checkout@v2
#             - name: Install Dependencies
#               run: |
#                     python -m pip install --upgrade pip
#                     pip install -r requirements.txt
#             - name: Build and Publish Docs
#               run: source publish_docs.sh