name: Docs
on: [push, pull_request, workflow_dispatch]
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: create venv
        run: python3 -m venv venv
      - name: Activate venv
        run: source venv/bin/activate
      - name: source venv/bin/activate && install python dependencies
        run: pip install -q maturin sphinx
      - name: Build rust
        run: source venv/bin/activate && maturin develop
      - name: Sphinx build
        run: sphinx-build python/pqp/docs/source/ _build
      - name: deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: _build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # - name: Deploy
      #   uses: peaceiris/actions-gh-pages@v3
      #   if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
      #   with:
      #     publish_branch: gh-pages
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: python/sherlock/docs/_build
      #     force_orphan: true
      #     enable_jekyll: false